### PR TITLE
Doc: Add mermaid graph of app architecture

### PR DESCRIPTION
**Pull request by niley7464**
This patch adds app architecture using mermaid graph.

### CODE REVIEW

**Comment by niley7464** [comment]
image

**Comment by niley7464** [comment]
reference : https://google-developer-training.github.io/android-developer-advanced-course-concepts/unit-6-working-with-architecture-components/lesson-14-architecture-components/14-1-c-architecture-components/14-1-c-architecture-components.html

This is a temporary diagram using the above reference.
Could I update it to match nns-android?
The quality of the diagram is not that pretty 🤔

**Comment by wooksong** [comment]
> reference : https://google-developer-training.github.io/android-developer-advanced-course-concepts/unit-6-working-with-architecture-components/lesson-14-architecture-components/14-1-c-architecture-components/14-1-c-architecture-components.html
> 
> This is a temporary diagram using the above reference. Could I update it to match nns-android? The quality of the diagram is not that pretty 🤔

@niley7464 It looks pretty but is not that informable:) It is not mandatory, I guess. If you want to include it next time, it would be OK (maybe...).

**Review by wooksong — APPROVED** [review]
LGTM:)

**Pull request merged**
