### PR TITLE
Documentation: Update SD fusing scripts

### PR DESCRIPTION
**Pull request by niley7464**
This patch updates SD fusing scripts for rpi.

### CODE REVIEW

**Review by wooksong — COMMENTED** [review]
Q1. Where did you import this?
Q2. Is [this](https://git.tizen.org/cgit/platform/kernel/u-boot/tree/scripts/tizen/sd_fusing.py?h=tizen) a new version or a different Python version?

**Comment by niley7464** [comment]
> Q1. Where did you import this? Q2. Is [this](https://git.tizen.org/cgit/platform/kernel/u-boot/tree/scripts/tizen/sd_fusing.py?h=tizen) a new version or a different Python version?

A1. I was originally using this file, but I uploaded an older version last time. 

A2. I will test python script. If it works well, let's delete shell scripts and add this link to the guide.
Thank you for finding newer version.

**Comment by niley7464** [comment]
I don't know the exact reason, but my Raspberry Pi won't boot when I use a Python script 😭

**Comment by wooksong** [comment]
> I don't know the exact reason, but my Raspberry Pi won't boot when I use a Python script 😭

OK. Never mind.

**Review by wooksong — APPROVED** [review]
LGTM!

**Pull request merged**
